# Use the latest version of Ubuntu as the base image
FROM ubuntu:latest

# Update the APT package manager
RUN apt-get update

# Upgrade any already installed packages
RUN apt-get upgrade -y

# Set the default command to execute when the container starts
CMD echo "Hello, World!"